server: 
  port: 9000
spring: 
  application:  
    name: spring-base #指定服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_base?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&userSSL=false
    username: tensquare
    password: tensquare
  jpa:
    database: MySQL
    show-sql: true
